import { google } from 'googleapis';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { createServerClient } from './supabaseServer';

const FIVE_MINUTES_MS = 5 * 60 * 1000;

async function getOAuth2Client(emailAccountId) {
  const sb = createServerClient();

  const { data: account, error } = await sb
    .from('email_accounts')
    .select('*')
    .eq('id', emailAccountId)
    .single();

  if (error || !account) throw new Error(`email_accounts row not found: ${emailAccountId}`);

  const oauth2 = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    process.env.GOOGLE_REDIRECT_URI
  );

  const tokenExpiresAt = new Date(account.token_expires_at).getTime();
  const needsRefresh = !tokenExpiresAt || tokenExpiresAt < Date.now() + FIVE_MINUTES_MS;

  if (needsRefresh && account.refresh_token) {
    oauth2.setCredentials({ refresh_token: account.refresh_token });
    const { credentials } = await oauth2.refreshAccessToken();
    const newExpiry = new Date(credentials.expiry_date || Date.now() + 3600 * 1000).toISOString();

    await sb.from('email_accounts').update({
      access_token: credentials.access_token,
      token_expires_at: newExpiry,
      updated_at: new Date().toISOString(),
    }).eq('id', emailAccountId);

    oauth2.setCredentials(credentials);
    console.log('[drive] using refreshed token:', credentials.access_token?.substring(0, 20));
  } else {
    oauth2.setCredentials({
      access_token: account.access_token,
      refresh_token: account.refresh_token,
      expiry_date: tokenExpiresAt,
    });
    console.log('[drive] using stored token:', account.access_token?.substring(0, 20), '| expires:', account.token_expires_at);
  }

  return oauth2;
}

export async function getDriveClient(emailAccountId) {
  const oauth2 = await getOAuth2Client(emailAccountId);
  return google.drive({ version: 'v3', auth: oauth2 });
}

export async function getOrCreateWorkHistoryFolder(drive, propertyFolderId) {
  const q = `'${propertyFolderId}' in parents and name = 'Work History' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`;
  const res = await drive.files.list({ q, fields: 'files(id,name)', pageSize: 1 });

  if (res.data.files && res.data.files.length > 0) {
    return res.data.files[0].id;
  }

  const created = await drive.files.create({
    requestBody: {
      name: 'Work History',
      mimeType: 'application/vnd.google-apps.folder',
      parents: [propertyFolderId],
    },
    fields: 'id',
  });
  return created.data.id;
}

export async function createTaskFolder(drive, parentFolderId, folderName) {
  const created = await drive.files.create({
    requestBody: {
      name: folderName,
      mimeType: 'application/vnd.google-apps.folder',
      parents: [parentFolderId],
    },
    fields: 'id',
  });
  return created.data.id;
}

export async function createIndexPdf({ taskNum, propCode, title, recordUrl, propertyName, createdAt, folderId, driveClient }) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // Letter

  const boldFont   = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const normalFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const orange = rgb(0xE8 / 255, 0x63 / 255, 0x0A / 255);
  const black  = rgb(0, 0, 0);

  const left    = 60;
  const lineH   = 24;
  let   y       = 700;

  const draw = (text, { bold = false, color = black, size = 11 } = {}) => {
    page.drawText(String(text ?? ''), {
      x: left, y,
      size,
      font: bold ? boldFont : normalFont,
      color,
    });
    y -= lineH;
  };

  const displayId = propCode ? `${propCode}-${taskNum}` : String(taskNum);
  const createdStr = (() => {
    if (!createdAt) return '';
    const d = new Date(createdAt);
    if (isNaN(d)) return '';
    const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
    const dd = String(d.getUTCDate()).padStart(2, '0');
    return `${mm}-${dd}-${d.getUTCFullYear()}`;
  })();
  const propLine = propertyName
    ? `${propertyName}${propCode ? ` (${propCode})` : ''}`
    : (propCode || '');

  draw('Anderson Commercial Properties', { bold: true, color: orange, size: 13 });
  y -= lineH; // blank line

  draw(`Record ID:  ${displayId}`,          { bold: true });
  draw(`Title:      ${title || ''}`,        {});
  draw(`Property:   ${propLine}`,           {});
  draw(`Created:    ${createdStr}`,         {});
  y -= lineH; // blank line

  draw('Open in SedonaCRM:', { bold: true });
  draw(recordUrl || '',     {});
  y -= lineH; // blank line

  draw('This document was auto-generated by SedonaCRM.', { color: rgb(0.5, 0.5, 0.5) });

  const pdfBytes  = await pdfDoc.save();
  const fileName  = `000_${displayId}_Info.pdf`;

  const { Readable } = await import('stream');
  const stream = Readable.from(Buffer.from(pdfBytes));

  const res = await driveClient.files.create({
    requestBody: {
      name:    fileName,
      mimeType: 'application/pdf',
      parents: [folderId],
    },
    media: {
      mimeType: 'application/pdf',
      body:     stream,
    },
    fields: 'id,webViewLink',
  });

  return { id: res.data.id, webViewLink: res.data.webViewLink, fileName };
}
